

parameters:
    cv_directory: '%kernel.project_dir%/public/uploads/cv'

services:
    _defaults:
        autowire: true
        autoconfigure: true
    App\:
        resource: '../src/'
    App\Security\UserChecker: ~
